### ISSUE TITLE
Eliminate `hdrline.c`s Global Config Variables

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#2825]
For more detailed info, see #2819.

`hdrline.c` contains code to format strings for the Index.

## Tasks

- [X] Create a branch of the form `devel/SHORT-NAME`
      This should be based on branch [`[devel/refactor]`](https://github.com/neomutt/neomutt/tree/devel/refactor) 
      e.g. `git fetch origin; git checkout -b devel/hdrline origin/devel/refactor`

- [X] Factor out hdrline's config.
      - Move the config definitions into a new array in `hdrline.c`
      - Register the new array in `init_variables()`

- [ ] Eliminate the config global variables
      - Locate all the users of the globals
      - Add a `ConfigSubset` parameter to all the functions from the `mutt_make_string()` to those functions.
        (The diagram below should help)
      - Replace the global variables with config helper functions, using the sub parameter.

<a href="https://flatcap.org/mutt/hdrline.svg"><img width="800" src="https://flatcap.org/mutt/hdrline.svg"></a>

**Comment by ngortheone** [comment]
@flatcap 
> This should be based on commit 9085b8d in branch [devel/index]

should this be changed to [devel/refactoring] ?

**Comment by flatcap** [comment]
> should this be changed to [devel/refactoring] ?

Yes, thanks.  Done.
This issue slightly preceded that branch.

**Comment by flatcap** [comment]
I've had another look.
It doesn't need to be as complicated as I suggested on IRC :-)

Config is used in `index_format_str()`, `make_from_prefix()`.
In `index_format_str()` we have a `Mailbox`, so we can use `m->sub`.
We can pass `m->sub` to `make_from()` and on to `make_from_prefix()`.

**Comment by paniash** [comment]
@flatcap Thanks for this. I'll see what I can do. :-)

**Comment by darrel-glud** [comment]
I think this was solved by https://github.com/neomutt/neomutt/commit/240e059e8c51ec5d3173529bd20c63a09455f276 .

**Comment by flatcap** [comment]
Thanks, @darrel-glud
